export const data = [
    {
        id: "one",
        url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg/270px-Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg",
        Name: "Mona Lisa",
        tag: "Leonardo Da Vinci",
    },
    {
        id: "two",
        url: "https://media.timeout.com/images/103166735/750/562/image.jpg",
        Name: "Girl with a Pearl Earring",
        tag: "Johannes Vermeer",
    },
    {
        id: "three",
        url: "https://media.timeout.com/images/103166739/750/562/image.jpg",
        Name: "The Starry Night",
        tag: "Vincent van Gogh",
    },
    {
        id: "four",
        url: "https://media.timeout.com/images/103166743/750/562/image.jpg",
        Name: "The Kiss,",
        tag: "Gustav Klimt",
    },
    {
        id: "five",
        url: "https://media.timeout.com/images/103166737/750/562/image.jpg",
        Name: "The Birth of Venus",
        tag: "Sandro Botticelli",
    },
    {
        id: "six",
        url: "https://media.timeout.com/images/103166741/750/562/image.jpg",
        Name: "Arrangement in Grey and Black No. 1",
        tag: "James Abbott McNeill Whistler",
    },
    {
        id: "seven",
        url: "https://media.timeout.com/images/103166745/750/562/image.jpg",
        Name: "The Arnolfini Portrait",
        tag: "Jan van Eyck",
    },
    {
        id: "eight",
        url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Joos_van_Craesbeeck_-The_Temptation_of_St_Anthony.jpg/800px-Joos_van_Craesbeeck_-The_Temptation_of_St_Anthony.jpg?20220702101247",
        Name: "The Temptation of Saint Anthony",
        tag: "Joos Van Craesbeeck",
    },
    {
        id: "nine",
        url: "https://media.timeout.com/images/103166747/750/562/image.jpg",
        Name: "The Garden of Earthly Delights",
        tag: "Hieronymus Bosch",
    },
    {
        id: "ten",
        url: "https://media.timeout.com/images/105293264/750/562/image.jpg",
        Name: "A Sunday Afternoon on the Island of La Grande Jatte",
        tag: "Georges Seurat",
    },
    {
        id: "eleven",
        url: "https://media.timeout.com/images/103166750/750/562/image.jpg",
        Name: "Les Demoiselles d’Avignon",
        tag: "Pablo Picasso",
    },
    {
        id: "twelve",
        url: "https://media.timeout.com/images/105222673/750/562/image.jpg",
        Name: "The Harvesters",
        tag: "Pieter Bruegel the Elder",
    },
    {
        id: "thirteen",
        url: "https://media.timeout.com/images/105222677/750/562/image.jpg",
        Name: "Le Déjeuner sur l’herbe",
        tag: "Édouard Manet",
    },
    {
        id: "fourteen",
        url: "https://upload.wikimedia.org/wikipedia/commons/3/30/Piet_Mondrian%2C_1942_-_Broadway_Boogie_Woogie.jpg",
        Name: "Broadway Boogie Woogie",
        tag: "Piet Mondrian",
    },
    {
        id: "fifteen",
        url: "https://www.afpradomuseum.org/media/images/picture_of_the_month/masterpieces_01.jpg",
        Name: "Las Meninas, or The Family of King Philip IV",
        tag: "Diego Rodríguez de Silva y Velázquez",
    },
    {
        id: "sixteen",
        url: "https://media.timeout.com/images/105222680/750/562/image.jpg",
        Name: "Guernica",
        tag: "Pablo Picasso",
    },
    {
        id: "seventeen",
        url: "https://media.timeout.com/images/105222679/750/562/image.jpg",
        Name: "The Naked Maja, circa",
        tag: "Francisco de Goya y Lucientes",
    },
    {
        id: "eighteen",
        url: "https://media.timeout.com/images/105222681/750/562/image.jpg",
        Name: "Grande Odalisque",
        tag: "Jean Auguste Dominique Ingres",
    },
    {
        id: "nineteen",
        url: "https://media.timeout.com/images/105222682/750/562/image.jpg",
        Name: "Liberty Leading the People",
        tag: "Eugène Delacroix",
    },
    {
        id: "twenty",
        url: "https://media.timeout.com/images/105222683/750/562/image.jpg",
        Name: "Impression, Sunrise",
        tag: "Claude Monet",
    },
    {
        id: "twenty-one",
        url: "https://media.timeout.com/images/105222684/750/562/image.jpg",
        Name: "Wanderer above the Sea of Fog",
        tag: "Caspar David Friedrich",
    },
    {
        id: "twenty-two",
        url: "https://media.timeout.com/images/105455055/750/562/image.jpg",
        Name: "Nude Descending a Staircase",
        tag: "Marcel Duchamp",
    },
    {
        id: "twenty-three",
        url: "https://media.timeout.com/images/105222685/750/562/image.jpg",
        Name: "The Raft of the Medusa",
        tag: "Théodore Géricault",
    },
    {
        id: "twenty-four",
        url: "https://media.timeout.com/images/105455060/750/562/image.jpg",
        Name: "Nighthawks",
        tag: "Edward Hopper",
    },
]
